name: packages/css-variants / test

on:
  push:
    paths:
      - 'packages/css-variants/**'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    paths:
      - 'packages/css-variants/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          check-latest: true

      - name: Install ğŸ”§
        run: yarn install --frozen-lockfile

      - name: Build ğŸ—ï¸
        run: yarn css-variants build

      - name: Lint ğŸ§
        run: yarn css-variants lint

      - name: Test ğŸš¨
        run: yarn css-variants test
